# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  - master
  
variables:
  BuildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Build Wordpress Theme'
  inputs:
    command: build
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config    # Relative to root of the repository
    #externalFeedCredentials: <Name of the NuGet service connection>

- task: DotNetCoreCLI@2
  displayName: 'Pack Wordpress Theme'
  inputs:
    command: pack
    projects: '**/*.csproj'
    nobuild: true

# Publish Build Artifacts
# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  displayName: 'Pubilsh Build Artifacts'